version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: movies
    ports:
      - "5432:5432"